#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/y2-intel/y2-go,github.com/stainless-sdks/y2-go"

echo "==> Running Go build"
go build ./...
